timeline-django/history-timeline/urls.py
from django.contrib import admin
from django.urls import (
    include,
    path,
)
from rest_framework import routers

from timeline import views


router = routers.DefaultRouter()
router.register(r"events", views.EventViewSet)
router.register(r"organizations", views.OrganizationViewSet)
router.register(r"persons", views.PersonViewSet)
router.register(r"timelines", views.TimelineViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('router/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls',  namespace='rest_framework')),
    path('api/', include("timeline.urls")),
]

timeline-django/timeline/urls.py
from . import views
from .api import v1
from django.urls import path

app_name = "timeline"
urlpatterns = [
    # path('', views.index, name="index"),
    path(
        'timeline/<int:timeline_id>/events',
        v1.TimelineEvents.as_view(),
        name="get_events"
    ),
]
 

timeline-django/timeline/models.py
from django.db import models
from typing import Optional


# Create your models here.
class OrganizationManager(models.Manager):
    def create_entity(self, name):
        origanization = self.create(name=name)
        return origanization


class Organization(models.Model):
    name = models.CharField(max_length=100)
    objects = OrganizationManager()

    def __str__(self):
        return self.name


class PersonManager(models.Manager):
    def create_person(self, name):
        person = self.create(name=name)
        return person


class Person(models.Model):
    name = models.CharField(max_length=100)
    organizations_involved = models.ManyToManyField(Organization, blank=True)
    objects = PersonManager()

    def __str__(self):
        return self.name


class EventManager(models.Manager):
    def create_event(self, name, date: Optional = None):
        event = self.create(name=name, date=date)
        return event


class Event(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField(null=True)
    description = models.TextField(null=True)
    persons_involved = models.ManyToManyField(Person, blank=True)
    organizations_involved = models.ManyToManyField(Organization, blank=True)

    objects = EventManager()

    def __str__(self):
        return self.name


class TimelineManager(models.Manager):
    def create_event(self, name, date: Optional = None):
        event = self.create(name=name, date=date)
        return event


class Timeline(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    events = models.ManyToManyField(Event, blank=True)

    objects = TimelineManager()

    def __str__(self):
        return self.name

timeline-django/timeline/views.py
from datetime import datetime
import logging

from django.http import Http404, HttpResponse
from django.template import loader
from django.shortcuts import render
from rest_framework import (
    viewsets,
    permissions,
)

from .models import Timeline, Event, Organization, Person
from .serializers import (
    TimelineSerializer,
    EventSerializer,
    OrganizationSerializer,
    PersonSerializer,
)


# Create your views here.
def index(request):
    events = Event.objects.order_by("name")
    context = {
        "events": events
    }
    template = loader.get_template("index.html")
    return HttpResponse(template.render(context, request))


class TimelineViewSet(viewsets.ModelViewSet):
    queryset = Timeline.objects.all().order_by("id")
    serializer_class = TimelineSerializer


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all().order_by("id")
    serializer_class = EventSerializer


class OrganizationViewSet(viewsets.ModelViewSet):
    queryset = Organization.objects.all().order_by("id")
    serializer_class = OrganizationSerializer


class PersonViewSet(viewsets.ModelViewSet):
    queryset = Person.objects.all().order_by("id")
    serializer_class = PersonSerializer


def detail(request, event_pk):
    try:
        event = Event.objects.get(pk=event_pk)
    except Event.DoesNotExist:
        raise Http404("Event does not exist")
    return render(request, "timeline/detail.html", {"event": event})


def form(request):
    return render(request, "timeline/form.html")


def submit_entry(request):
    data = request.POST
    new_organization = None
    new_event = Event.objects.create_event(name=data["event_name"])
    if "organization" in data.keys():
        new_organization = Organization.objects.create_entity(name=data["organization"])
        new_organization.event_involved = new_event
        new_organization.save()
    if "person" in data.keys():
        new_person = Person.objects.create_person(name=data["person"])
        new_person.event_involved = new_event
        if new_organization:
            new_person.organization_involved = new_organization
        new_person.save()
    return HttpResponse(f"Created new event {new_event.name}")

timeline-django/timeline/templates/timeline/detail.html
<h1>{{event.name}}</h1>
<h2>{{event.date}}</h2>
<ul>
{% for person in event.person_set.all %}
    <li>{{person.name}}</li>
{% endfor %}
</ul>

timeline-django/timeline/templates/timeline/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="styles.css"></link>
</head>
<body>
<form action="{% url 'timeline:submit_entry'%}" method="post">
{% csrf_token %}
    <fieldset>
        <h1>Fill in Event Details</h1>
        <label>Name:</label>
        <input type="text" name="event_name">
        <br>
            <label>Involved Organization:</label>
            <input type="text" name="organization">
        </br>
        <br>
            <label>Involved Person:</label>
            <input type="text" name="person">
        </br>
    </fieldset>
    <input type="submit" value="Submit">
</form>
</body>
</html>

timeline-django/timeline/templates/timeline/world-timeline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css"/>
</head>
<body>
<div class="timeline">
  {% if events %}
    {% for e in events %}
      <div class="container left">
        <div class="content">
          <li><a href="{% url 'timeline:detail' e.pk %}">{{e.name}}</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No Events Available</p>
  {% endif %}
<!--  <div class="container right">-->
<!--    <div class="content">-->
<!--      <h2>2016</h2>-->
<!--      <p>Lorem ipsum dolor sit amet, quo ei simul congue exerci, ad nec admodum perfecto mnesarchum, vim ea mazim fierent detracto. Ea quis iuvaret expetendis his, te elit voluptua dignissim per, habeo iusto primis ea eam.</p>-->
<!--    </div>-->
<!--  </div>-->
</div>

</body>
</html>